services:
  - type: web
    name: bigwhale-backend
    env: python
    startCommand: gunicorn app_corrigido:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER
        value: true