services:
  - type: web
    name: bigwhale-backend
    env: python
    runtime: python-3.11.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:application
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_SECRET_KEY
        value: uma-chave-secreta-bem-dificil-de-adivinhar-987654
      - key: AES_ENCRYPTION_KEY  
        value: chave-criptografia-api-bitget-nautilus-sistema-seguro-123456789
      - key: FLASK_ENV
        value: production
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_1BYR0SrkEmay1AvbYgzBX01mTaqEYLNb