services:
  - type: web
    name: bigwhale-backend
    env: python
    buildCommand: pip install -r requirements.txt && pip install psycopg2-binary==2.9.9
    startCommand: python app_simples.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: true