services:
  - type: web
    name: bigwhale-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: AES_ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bigwhale-db
          property: connectionString

databases:
  - name: bigwhale-db
    databaseName: bigwhale
    user: bigwhale_user
